import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navigation from "../components/Navigation";
import MainPage from "../components/MainPage";
import Nav from "../components/Nav";
import Coffee from "../components/Coffee";
import Featured from "../components/Featured";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navigation />
      <MainPage /> */}
      <Nav />
      <Coffee />
      <Featured />
    </div>
  );
}
